name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23lipMmRs0BpUEVoCu"
GITHUB_OWNER = "TheMechanic-K"
GITHUB_REPO = "knav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://knav.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://knav.pages.dev/"

